# Training configs for Seg

dataset : Oil Dataset
n_classes : 2
channels : 7
ignore_index : 255
net : UNet
optimizer : SGD
scheduler : StepLR
lr : 0.001
batchsize : 4
start_epoch : 0
end_epoch : 150
result_dir : "./eventfiles-UNet-channels7"
criterion : CrossEntropy
logIterval : 20
valIterval : 2
resume :
  flag : True
  state_path : "./eventfiles-UNet-channels7/UNet-ep.pth"