# Training configs for Seg

dataset : Oil Dataset
channels : 7
n_classes : 2
ignore_index : 255
net : fcns
optimizer : SGD
scheduler : StepLR
lr : 0.0001
batchsize : 4
start_epoch : 0
end_epoch : 150
result_dir : "./eventfiles-fcns-channels7"
criterion : CrossEntropy
logIterval : 20
valIterval : 2
resume : 
  flag : True
  state_path : "./eventfiles-fcns-channels7/fcns-ep126.pth"